# Adapted from https://github.com/marketplace/actions/deploy-pr-preview.
name: Deploy PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: npm ci && npx tsc && npx vite build --base=https://allen-cell-animated.github.io/nucmorph-colorizer/pr-preview/pr-${{github.event.pull_request.number}}/

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/
